services:
  - type: web
    name: voice-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn flask_api:app
    envVars:
      - key: SF_USERNAME
        value: your_salesforce_username
      - key: SF_PASSWORD
        value: your_salesforce_password
      - key: SF_TOKEN
        value: your_salesforce_security_token
      - key: GEMINI_API_KEY
        value: your_gemini_api_key
